Updated WP Plugin file and Project Root readme
nuxeo/nuxeo-wordpress-plugin pull request #1
Opened 2016-11-10 01:11 UTC by ladland

- Updated README.md to provide instructions to install deps.

- Updated nuxeo-plugin.php to fix 500 error due to unknown method on line 179

2016-11-10 01:11 UTC, nuxeojenkins commented
From the blame information on this pull request, potential reviewers: @pgmillon, @ldreuillat

2016-11-14 17:47 UTC, pgmillon requested changes
Hi,
Thanks a lot for your interest in the Wordpress plugin !
The twig template improvement is great.
I'll fill the README in the next days to match with our template (http://doc.nuxeo.com/display/CORG/README+Template).
Can you remove + ignore the mac .DS_Store files ?

2016-11-15 00:03 UTC, ladland commented
The requested changes have been made

2016-11-16 15:42 UTC, pgmillon commented
I picked up your commits (you commited your wordpress folder) and updated the README.

2016-11-16 15:42 UTC, closed without merging